name: CI

on:
  push:

jobs:
  run-tests:
    strategy:
      # Do not fail fast, so we can see all errors from the unit/integration tests
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    name: Tests
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Windows support.
      - uses: ilammy/msvc-dev-cmd@v1

      - uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "luajit-2.0.5"

      - name: Run tests
        run: lua ./tests/main.lua

